namespace GloryLikeWebApp.Models.Employer;

public static class EmployeeBenefitCatalog
{
    public static IReadOnlyList<string> All { get; } = new[]
    {
        "Annual Performance Bonus",
        "Quarterly Performance Bonus",
        "Sales / Commission Bonus",
        "Sign-on Bonus",
        "Retention Bonus",
        "Referral Bonus",
        "Spot Bonus / Recognition Award",
        "Annual Salary Review",
        "Long-Service Award",
        "Profit Sharing",
        "Stock Options / Equity",
        "Employee Share Purchase Plan",
        "Housing Allowance",
        "Transportation Allowance",
        "Fuel Allowance",
        "Mobile Phone Allowance",
        "Internet Allowance",
        "Meal Allowance",
        "Representation Allowance",
        "Relocation Allowance",
        "Health Care Benefit",
        "Private Medical Insurance",
        "Dental Insurance",
        "Vision Insurance",
        "Life Insurance",
        "Accident Insurance",
        "Critical Illness Insurance",
        "Family Medical Insurance",
        "Mental Health Support",
        "Employee Assistance Program (EAP)",
        "Psychological Counselling",
        "Annual Health Check-up",
        "Gym Membership",
        "Sports Allowance",
        "Wellness Allowance",
        "Fitness Programs",
        "Corporate Sports Activities",
        "Paid Annual Leave",
        "Additional Annual Leave",
        "Paid Sick Leave",
        "Maternity Leave",
        "Paternity Leave",
        "Parental Leave",
        "Marriage Leave",
        "Bereavement Leave",
        "Birthday Leave",
        "Study Leave",
        "Volunteer Leave",
        "Unpaid Leave",
        "Sabbatical Leave",
        "Additional Days Off for Long Service",
        "Flexible Working Hours",
        "Remote Work",
        "Hybrid Working",
        "Work-from-Anywhere Policy",
        "Flexible Start and Finish Times",
        "Reduced Working Hours",
        "Summer Working Hours",
        "Additional Work-from-Home Days",
        "Professional Training",
        "External Courses",
        "Online Learning Platforms",
        "Professional Certification Sponsorship",
        "Conference Participation",
        "Workshop Participation",
        "Language Courses",
        "Leadership Development Programs",
        "Coaching",
        "Mentoring",
        "Individual Development Budget",
        "Tuition Reimbursement",
        "MBA / Master’s Degree Sponsorship",
        "Career Development Programs",
        "Internal Mobility Opportunities",
        "Talent Programs",
        "High-Potential Employee Programs",
        "Succession Planning",
        "Leadership Pipeline Programs",
        "Employee Recognition Programs",
        "Employee of the Month / Year Awards",
        "Service Anniversary Recognition",
        "Company Car",
        "Car Allowance",
        "Fuel Card",
        "Corporate Taxi",
        "Shuttle Service",
        "Parking Space",
        "Public Transportation Reimbursement",
        "Business Travel Benefits",
        "Relocation Support",
        "Free Meals",
        "Subsidized Meals",
        "Meal Vouchers",
        "Lunch Allowance",
        "Free Coffee and Snacks",
        "Corporate Cafeteria",
        "Company Laptop",
        "Company Mobile Phone",
        "Corporate SIM Card",
        "Home Office Equipment",
        "Home Office Allowance",
        "Internet Reimbursement",
        "Technology Allowance",
        "Employee Discounts on Company Products",
        "Childcare Allowance",
        "Kindergarten / Nursery Support",
        "Education Allowance for Children",
        "Newborn Bonus",
        "Marriage Bonus",
        "Family Events",
        "Summer Camps for Employees’ Children",
        "Corporate Discounts",
        "Partner Discounts",
        "Cinema / Entertainment Discounts",
        "Travel Discounts",
        "Corporate Events",
        "Team-Building Activities",
        "Company Retreats",
        "Holiday Gifts",
        "Birthday Gifts",
        "New Year Gifts",
        "Corporate Merchandise",
        "Recognition Gifts",
        "Executive Medical Insurance",
        "Company Car with Driver",
        "Enhanced Housing Allowance",
        "Enhanced Relocation Package",
        "Executive Bonus Scheme",
        "Long-Term Incentive Plan (LTIP)",
        "Stock / Equity Program",
        "Executive Life Insurance",
        "Business-Class Travel",
        "Executive Education / Coaching",
        "Club Membership",
        "Representation Expenses",
        "Pension / Retirement Contributions",
        "Voluntary Pension Plan",
        "Financial Wellbeing Programs",
        "Employee Loans",
        "Preferential Banking Conditions",
        "Corporate Credit Card",
        "Legal Assistance",
        "Visa / Immigration Support",
        "Relocation Services",
        "Discounts on Company Services",
        "Corporate Mobile Plans",
        "Employee Referral Program"
    };
}
